version: '3.0'
services:
  producer:
    build: producer
    env_file:
      - ./env.conf

  consumer:
    build: consumer
    env_file:
      - ./env.conf

  lagreader:
    build: lagreader
    env_file:
      - ./env.conf
networks:
  default:
    external:
      name: sensor-network