version: '3.0'
services:
  producer:
    build: producer
    env_file:
      - ./env.conf

  consumer:
    build: consumer
    env_file:
      - ./env.conf

  lagreader:
    build: lagreader
    env_file:
      - ./env.conf
  webapi:
    build: webapi
    env_file:
      - ./env.conf
    ports:
      - "5555:5000"
  web:
    build: web
    env_file:
      - ./env.conf
    ports:
      - "8010:80"
networks:
  default:
    external:
      name: sensor-network